<Project>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>NoNam</Authors>
    <Product>JlptTrainer</Product>
    <Company>JlptTrainer</Company>
  </PropertyGroup>

  <!-- áp riêng cho project trong thư mục tests/ -->
  <PropertyGroup Condition="$(MSBuildProjectDirectory.Contains('tests'))">
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

</Project>
